"""make name required

Revision ID: 5be401e219be
Revises: 8428a40138c0
Create Date: 2026-04-26 00:36:23.428464

"""
from collections.abc import Sequence

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5be401e219be'
down_revision: str | None = '8428a40138c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("UPDATE users SET name = '(미입력)' WHERE name IS NULL")
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###
