"""init user domain

Revision ID: 8428a40138c0
Revises: 
Create Date: 2026-04-26 00:10:06.203135

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8428a40138c0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('calendar_type', sa.Enum('solar', 'lunar', name='calendartype'), nullable=False),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('birth_time_unknown', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saju_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fortuneteller_request', sa.JSON(), nullable=False),
    sa.Column('fortuneteller_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_saju_results_user_id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('survey_version', sa.String(length=16), nullable=False),
    sa.Column('step1_slugs', sa.JSON(), nullable=False),
    sa.Column('step2_slugs', sa.JSON(), nullable=False),
    sa.Column('step3_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_user_id'), 'surveys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_user_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_table('saju_results')
    op.drop_table('users')
    # ### end Alembic commands ###
