"""add share_code to paid_report

Revision ID: f3b6ba2f1b8e
Revises: 4dda5005e680
Create Date: 2026-05-14 10:06:30.529125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b6ba2f1b8e'
down_revision: Union[str, None] = '4dda5005e680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent — 첫 fail에서 ADD COLUMN은 통과했지만 CREATE INDEX에서 실패한 운영 DB
    # 상태도 안전하게 처리. 1) 컬럼 있나 검사 후 추가 2) 빈값 row UUID 백필
    # 3) NOT NULL alter 4) INDEX 있나 검사 후 생성.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [c['name'] for c in insp.get_columns('paid_reports')]
    indexes = [i['name'] for i in insp.get_indexes('paid_reports')]

    if 'share_code' not in columns:
        op.add_column('paid_reports', sa.Column('share_code', sa.String(length=32), nullable=True))

    op.execute("UPDATE paid_reports SET share_code = REPLACE(UUID(), '-', '') WHERE share_code IS NULL OR share_code = ''")

    op.alter_column('paid_reports', 'share_code', existing_type=sa.String(length=32), nullable=False)

    if 'ix_paid_reports_share_code' not in indexes:
        op.create_index(op.f('ix_paid_reports_share_code'), 'paid_reports', ['share_code'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paid_reports_share_code'), table_name='paid_reports')
    op.drop_column('paid_reports', 'share_code')
    # ### end Alembic commands ###
