"""add share_code to paid_report

Revision ID: f3b6ba2f1b8e
Revises: 4dda5005e680
Create Date: 2026-05-14 10:06:30.529125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b6ba2f1b8e'
down_revision: Union[str, None] = '4dda5005e680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 운영 DB에 기존 paid_reports row가 있을 경우를 위해 3단계로:
    # 1. nullable 컬럼으로 추가
    # 2. 기존 row에 MySQL UUID() (32자 hex)로 채움
    # 3. NOT NULL 강제 후 UNIQUE INDEX
    op.add_column('paid_reports', sa.Column('share_code', sa.String(length=32), nullable=True))
    op.execute("UPDATE paid_reports SET share_code = REPLACE(UUID(), '-', '') WHERE share_code IS NULL")
    op.alter_column('paid_reports', 'share_code', existing_type=sa.String(length=32), nullable=False)
    op.create_index(op.f('ix_paid_reports_share_code'), 'paid_reports', ['share_code'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paid_reports_share_code'), table_name='paid_reports')
    op.drop_column('paid_reports', 'share_code')
    # ### end Alembic commands ###
